# Generated by Django 3.2.5 on 2021-07-29 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalho', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('ingresso', models.CharField(max_length=7, verbose_name='ingresso')),
                ('situacao', models.CharField(max_length=10, verbose_name='situacao')),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
