# Generated by Django 3.2.5 on 2021-07-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalho', '0002_auto_20210728_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='nota',
            field=models.IntegerField(default=0, verbose_name='Nota - Web Avançado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='ingresso',
            field=models.CharField(max_length=7, verbose_name='Período de Ingresso'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='situacao',
            field=models.CharField(max_length=10, verbose_name='Situação'),
        ),
    ]
